<div id="container-email" style="background:#F7F7F8;font-family:'Open Sans', sans-serif;margin:auto;padding-bottom:20px;padding-top:20px;width:900px;">
    <div id="container-head" style="background:#FFF;margin:auto;padding:15px;width:585px;">
        <div id="social-networks" style="color:#727176;display:inline-block;float:right;">
        
            <?php echo $this->translate('follow_us')?>:
            
            <ul style="display:inline-block;list-style:none;vertical-align:middle;">
                <li style="display:inline-block;list-style:none;color:#727176;">
                    <a href="https://www.facebook.com/ParadisoSolutions" target="_blank"><img src="http://www.paradisosolutions.com/images/facebook-email.png" alt=""></a>
                </li>
                <li style="display:inline-block;list-style:none;color:#727176;">
                    <a href="https://twitter.com/ParadisoSol" target="_blank"><img src="http://www.paradisosolutions.com/images/twitter-email.png" alt=""></a>
                </li>
                <li style="display:inline-block;list-style:none;color:#727176;">
                    <a href="https://plus.google.com/115726699434928841525/posts" target="_blank"><img src="http://www.paradisosolutions.com/images/plus-email.png" alt=""></a>
                </li>
                <li style="display:inline-block;list-style:none;color:#727176;">
                    <a href="http://www.linkedin.com/company/paradiso-solutions" target="_blank"><img src="http://www.paradisosolutions.com/images/in-email.png" alt=""></a>
                </li>
            </ul>
        </div>
        <img style="width:147px;" id="logo" src="http://www.paradisosolutions.com/images/logo-paradiso-solutions.png" alt="Paradiso">
        <h2 style="font-size:18px;margin:auto;margin-top:30px;text-align:center;"></h2>
    </div>
    <div id="container-body" style="background:#FFF;margin:auto;width:615px;font-size:18px;margin-top:20px;padding-bottom:0px;height:210px;">
        <div id="message">
            <div style="float:left;font-family:'Open Sans',sans-serif;font-size:18px;padding:25px;padding-top:15px;width:260px;">
                <?php $this->Communicator()->printMessage() ?> 
            </div>
        </div>
        <img style="float:right;" src="http://paradisosolutions.com/images/thanks-image.png" alt="Paradiso">
    </div>
</div>