<?php
$com = $this->Communicator();
?>

<?php $this->headStyle()->captureStart() ?>
#edit_instance{cursor:pointer;display:none}
#instance{width:200px}
#loader{text-align:center;visibility:hidden}
#alert{display:none}
<?php $this->headStyle()->captureEnd() ?>

<div id="form">
   <h1><?php echo $this->translate('Welcome to Paradiso LMS') ?></h1>
   <p><?php echo $this->translate('Once you complete this form, we will create an account for you. Please specify a correct email address.') ?></p>

   <div id="container">
   
      <h2><?php echo $this->translate('Create Account')?> <span><?php echo $this->translate('Please fill in all required fields *') ?></span></h2>
      
      <form method="post" action="<?php echo $this->url('home') ?>?type=<?php echo $this->type?>" id="form_element" enctype="multipart/form-data">
      
         <div id="alert"><?php $com->printMessage() ?></div>
         <div id="loader"><img src="<?php echo $this->basePath('img/loader.gif') ?>"> 
         <?php echo $this->translate('please_wait') ?></div>

         <div class="form-control-2 required large <?php $com->printErrorClass('email'); ?>">
            <label><?php echo $this->translate('Email address')?>*</label>
            <input type="text" id="email" name="email" value="<?php echo $this->escapeHtml($this->email) ?>" required="required">
            <?php $com->printFieldErrors('email'); ?>
         </div>
         
         
         <div id="instance_container" class="form-control-2 required <?php $com->printErrorClass('instance'); ?>">
            <label><?php echo $this->translate('Instance name')?>*</label>
            
            <input 
                class="form-control" 
                disabled="disabled"
                type="text" 
                id="instance_label" 
                name="instance_label" 
                value="<?php echo $this->escapeHtml($this->instance) ?>" >.paradisolms.com 
                
                <input type="hidden" id="instance" name="instance" value="<?php echo $this->escapeHtml($this->instance) ?>" >
            
            <img id="edit_instance" 
                src="<?php echo $this->basePath('img/edit.png') ?>" 
                alt="<?php echo $this->translate('edit_instance_name') ?>" 
                title="<?php echo $this->translate('edit_instance_name') ?>">
            
            <?php $com->printFieldErrors('instance'); ?>
         </div>

         <div class="form-control-2 required <?php $com->printErrorClass('password'); ?>">
            <label><?php echo $this->translate('Password')?>*</label>
            <input type="password" name="password" required="required">
            <?php $com->printFieldErrors('password'); ?>
         </div>

         <div class="form-control-2 required large <?php $com->printErrorClass('first_name'); ?>">
            <label><?php echo $this->translate('First name')?>*</label>
            <input type="text" name="first_name" value="<?php echo $this->escapeHtml($this->first_name) ?>" required="required">
            <?php $com->printFieldErrors('first_name'); ?>
         </div>

         <div class="form-control-2 required large <?php $com->printErrorClass('last_name'); ?>">
            <label><?php echo $this->translate('Last name')?>*</label>
            <input type="text" name="last_name" value="<?php echo $this->escapeHtml($this->last_name) ?>" required="required">
            <?php $com->printFieldErrors('last_name'); ?>
         </div>
         
         <div class="form-control-2 required <?php $com->printErrorClass('logo'); ?>">
            <label><?php echo $this->translate('Logo')?></label>
            <input type="file" name="logo" />
            <div id="supported_formats_label">
                <?php echo $this->translate('supported_formats')?><br>
            </div>
            
            <div id="recommended_size_label">
                <?php echo $this->translate('recommended_size')?><br>
                <label>
                    <input type="checkbox" name="resize_logo" value="1" <?php echo $this->resize_logo ? 'checked="checked"' : '' ?>>
                    <?php echo $this->translate('resize_logo_label')?>
                </label>
                <a 
                    tabindex="0" 
                    class="help" 
                    role="button" 
                    data-toggle="popover" 
                    data-trigger="focus" 
                    
                    data-content='<?php echo $this->translate('resizing_recommendation')?>'>
                    <i class="fa fa-question-circle"></i>
                </a>
            </div>
            
            <?php $com->printFieldErrors('logo'); ?>
         </div>

         <div class="form-control-2" id="submit" style="margin-top:10px">
            <input type="submit" id="submit" value="<?php echo $this->translate('Create account')?>">
            <button type="button" onclick="window.history.back();"><?php echo $this->translate('Cancel')?></button>
         </div>

      </form>
   </div>
</div>


<script type="text/javascript">
    var $alert = null;
    var $loader = null;
    $('.help').popover({html:true});
    function show_loader()
    {
        $loader.css("visibility", 'visible');
    }
    
    function hide_loader()
    {
        $loader.css("visibility", 'hidden');
    }
    
    function blur_email()
    {
        $("#instance_label").attr("disabled", "disabled");
            
        var $self = $("#email");
        var email = $self.val();
        
        email = email.toLowerCase();
        $self.val(email);
        
        var exploded = email.split("@");
        
        if(2 == exploded.length)
        {
            exploded = exploded[1].split(".");
            if(exploded.length > 1)
            {
                $("#instance").val(exploded[0]);
                $("#instance_label").val(exploded[0]);
                $("#edit_instance").show();
            }
            else
            {
                $("#edit_instance").hide();
                $("#instance").val('');
                $("#instance_label").val('');
            }
        }
        else
        {
            $("#edit_instance").hide();
            $("#instance").val('');
            $("#instance_label").val('');
        }
    }

    jQuery(function() {
    
        $alert = $("#alert");
        $loader = $("#loader");
        
        $("#edit_instance").click(function() {
        
            var $self = $(this);
            
            $self.hide();
            
            show_loader();
            
            var url = "<?php echo $this->url('ajax', array('action' => 'can-edit-instance'));?>";
            var data = {email: $("#email").val()};
            
            $.post(url, data, function(response) {
            
                hide_loader();
                $self.show();
                
                if(response.success)
                {
                    $("#instance_label").removeAttr("disabled");
                    $("#instance").focus();
                }
                else
                {
                    $("#instance_label").attr("disabled", "disabled");
                    
                    var $div = $alert.find("div.alert");
                    $div.html("Sorry, you can't edit the instance name.").css("padding", "0px 10px");
                    $alert.show();
                }
            });

        });
        
        $("#email").blur(blur_email);
        
        
        $("#form").submit(function() {
            var v = $("#instance_label").val();
            $("#instance").val(v);
        })
    });

    <?php if($this->is_post) : ?>
        $("#edit_instance").show();
    <?php endif; ?>
    
    <?php if($this->is_post && !$com->isSuccess()) : ?>
        $("#alert").show();
    <?php endif; ?>
    
    
    <?php if($this->is_post && $com->isSuccess()) : ?>

        function check_instance_created(done, calls)
        {
            show_loader();
            
            $("#form_element :input").prop("disabled", true);
            
            $("#target :input").prop("disabled", true);
            
            var max_calls = 200;
            var url = "<?php echo $this->url('ajax', array('action' => 'check-instance-created'));?>";

            if(calls >= max_calls)
            {
                hide_loader();
                
                var $div = $alert.find("div.alert");
                $div.html("There was an unexpected error, please try again or contact support@paradisosolutions.com").css("padding", "0px 10px");
                $alert.show();
                
                $("#form_element :input").prop("disabled", false);
                
                return false;
            }
            
            if (done) 
            {
                hide_loader();
                $alert.show();
                
                $("#form_element :input").prop("disabled", false);
                
                return true;
            }
            
            $.ajax({
                url: url
                ,type: "POST"
                ,data: { website : "<?php echo $this->website?>" }
                ,success: function(data)
                {
                    console.log(data.success);
                    
                    if(!calls)
                    {
                        calls = 1;
                    }
                    else
                    {
                        ++calls;
                    }
                    
                    check_instance_created(data.success, calls);
                }
            });
        }

        jQuery(function() {
            check_instance_created(false, 1);
        });

    <?php endif; ?>

</script>



