Executing...
<script>
jQuery(function() {
    <?php if($this->instances) : ?>
        <?php foreach($this->instances as $row) : ?>
            $.ajax({
                type: "GET",
                url:"http://<?php echo $row->domain ?>/admin/cron.php",
                data: "{}",
                async: true,
                dataType: "text",
                success: function( data ) {
                    
                }
            }); 
        <?php endforeach;?>
    <?php endif; ?>
});
</script>
<p>Done!</p>
