<div id="text-top">
    <h2><?php echo $this->translate('try_free'); ?></h2>
</div>

<div id="head-form">
    <h3>
        <?php if(!$this->internal) : ?>
            <?php echo $this->translate('test_begin'); ?>
        <?php endif; ?>
    </h3>
</div>

<div id="form">
    <h1><?php echo $this->translate('welcome_message') ?></h1>
   
    <div id="container" style="margin-top:50px">
        <h2><?php echo $this->translate('freemium_account_created')?></h2>
    </div>
</div>

<script>

jQuery(function() {
    var message = "<?php echo $this->translate('freemium_account_created')?>";
    //alert(message);
});

</script>
