<?php
$com = $this->Communicator();
$userId = $this->GlobalVars('identity.id', 0);
?>

<div class="row">
    <div class="col-lg-4">
        <ul>
            <li>
                <a href="<?php echo $this->url('backend', array('controller' => 'sql', 'action' => 'index')); ?>">SQL</a>
            </li>
            <li>
                <a href="<?php echo $this->url('backend', array('controller' => 'instance', 'action' => 'approval-pending')); ?>">Approval pending</a>
            </li>
            <li>
                <a href="<?php echo $this->url('backend', array('controller' => 'instance', 'action' => 'list')); ?>">Instances</a>
            </li>
            <!--li>
                <a onclick="return _confirm()" href="<?php echo $this->url('backend', array('controller' => 'instance', 'action' => 'delete-free-db')); ?>">Delete free databases</a>
            </li-->
        </ul>
    </div>
</div>

<script>
function _confirm()
{
	return confirm("Please confirm that you want to delete ALL free databases.\n This action can't be undone.");
}
</script>
